// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 09/06/2026, 19:04:21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/plugins/**/*.{js,ts,mjs}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/composables/**/*.{js,ts,mjs}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/utils/**/*.{js,ts,mjs}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/mnt/Dados/Dev/VSCODE/mea-ecclesia-catholic/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;