export type KeywordLink = {
  to: string;
  translationKey?: string;
  text?: string;
  class?: string;
  external?: boolean;
};

// Doutrina, história e páginas temáticas ficam reunidas neste grupo.
const doctrineLinks: Record<string, KeywordLink> = {
  dever: { to: "/catecismo" },
  abstinencia: { to: "/catecismo" },
  jejum: { to: "/catecismo" },
  idolatria: { to: "/imagens-e-idolatria" },
  imagens_sagradas: { to: "/imagens-e-idolatria" },
  ressurreicao: { to: "/artigos" },
  tradicao: { to: "/tradicao-e-magisterio" },
  texto_apocrifo: { to: "/apocrifos" },
  papado: { to: "/papado" },
  jesus_cristo: { to: "/" },
  anunciacao: { to: "/historia" },
  apostolica: { to: "/sucessao-apostolica" },
  arcanjo_gabriel: { to: "/anjos" },
  arcebispos_maiores: { to: "/igrejas-orientais" },
  arianismo: { to: "/tradicao-e-magisterio" },
  arquidiocese: { to: "/estrutura#arcebispos" },
  arquidioceses: { to: "/estrutura#arcebispos" },
  bento_xvi: { to: "/papado" },
  celibato: { to: "/catecismo" },
  concilio_efeso: { to: "/tradicao-e-magisterio" },
  concilio_niceia: { to: "/tradicao-e-magisterio" },
  concilio_constantinopla: { to: "/tradicao-e-magisterio" },
  conclave: { to: "/papado" },
  diocese: { to: "/estrutura#bispos-diocesanos" },
  dioceses: { to: "/estrutura#bispos-diocesanos" },
  e_do_filho: { to: "/termologia-catolica#filioque" },
  homens_celibatarios: { to: "/catecismo" },
  idade_media: { to: "/historia" },
  igreja_triunfante: { to: "/intercessao-e-mediacao" },
  igrejas_orientais: { to: "/igrejas-orientais" },
  igrejas_orientais_catolicas: { to: "/igrejas-orientais" },
  intercede: { to: "/intercessao-e-mediacao" },
  intercessao: { to: "/intercessao-e-mediacao" },
  intercessao_santos: { to: "/intercessao-e-mediacao" },
  mae_deus: { to: "/intercessao-e-mediacao" },
  pai_1: { to: "/trindade", translationKey: "palavras_chave.pai" },
  pai_2: { to: "/trindade", translationKey: "palavras_chave.pai" },
  papa: { to: "/papado" },
  paroquia: { to: "/estrutura#paroco" },
  paroquias: { to: "/estrutura#paroco" },
  patriarcas: { to: "/igrejas-orientais" },
  pecados: { to: "/catecismo" },
  profetas: { to: "/livros" },
  salmos: { to: "/livros" },
  sucessao_apostolica: { to: "/sucessao-apostolica" },
  theotokos: { to: "/termologia-catolica#theotokos" },
  vida_consagrada: { to: "/estrutura#vida-consagrada" },
  visitacao: { to: "/historia" },
  sagrada_escritura: { to: "/escritura" },
  filipenses: { to: "/escritura" },
  evangeliario: { to: "/escritura" },
  pecados_veniais: { to: "/catecismo" },
  pecados_mortais: { to: "/catecismo" },
  espirito_santo: { to: "/trindade" },
  santissima_trindade: { to: "/trindade" },
  pai: { to: "/trindade" },
  filho: { to: "/trindade" },
  sagradas_escrituras: { to: "/escritura" },
  antigo_testamento: { to: "/escritura" },
  atos_apostolos: { to: "/escritura" },
  salmo: { to: "/escritura" },
  cartas_apostolicas: { to: "/escritura" },
  apocalipse: { to: "/escritura" },
  virgem_maria: { to: "/dogmas-marianos" },
  cristo: { to: "/trindade" },
  herodes: { to: "/personagens-historicos" },
  moises: { to: "/personagens-historicos" },
  elias: { to: "/personagens-historicos" },
  atos_dos_apostolos: { to: "/escritura" },
  apostolos: { to: "/sucessao-apostolica" },
  profissao_fe: { to: "/catecismo" },
  credo_apostolos: { to: "/catecismo" },
  credo_niceno: { to: "/catecismo" },
  concilios_ecumenicos: { to: "/tradicao-e-magisterio" },
  transubstanciacao: { to: "/catecismo" },
  misterio_fe: { to: "/milagres-eucaristicos" },
};

// Aqui ficam a Missa, os sacramentos, as orações e o calendário litúrgico.
const liturgyLinks: Record<string, KeywordLink> = {
  rito: { to: "/ritos" },
  batalha_epiritual: { to: "/oracoes" },
  batalha_espiritual: { to: "/oracoes", translationKey: "palavras_chave.batalha_epiritual" },
  sinal_da_cruz: { to: "/oracoes" },
  devocao: { to: "/artigos-religiosos" },
  ave_maria: { to: "/oracoes" },
  ave_marias: { to: "/oracoes" },
  aparicoes: { to: "/artigos-religiosos" },
  ato_penitencial: { to: "/missa#estrutura-da-santa-missa" },
  batizado: { to: "/sacramentos" },
  batizados: { to: "/sacramentos" },
  celebracao: { to: "/missa" },
  celebracoes: { to: "/missa" },
  comunhao: { to: "/missa#comunhao" },
  confissao: { to: "/sacramentos" },
  confissoes: { to: "/sacramentos" },
  consagrar_eucaristia: { to: "/missa#consagracao" },
  evangelho: { to: "/missa#evangelho" },
  leituras: { to: "/missa#ciclo-das-leituras" },
  liturgia: { to: "/missa" },
  liturgia_horas: { to: "/ritos" },
  liturgias: { to: "/missa" },
  liturgica: { to: "/missa#estrutura-da-santa-missa" },
  matrimonio: { to: "/sacramentos" },
  missa: { to: "/missa" },
  missas: { to: "/missa" },
  objetos: { to: "/artigos-religiosos" },
  ordem: { to: "/sacramentos" },
  proclamacao_evangelho: { to: "/missa#liturgia-da-palavra" },
  proclamar_evangelho: { to: "/missa#evangelho" },
  sacramento_confissao: { to: "/sacramentos" },
  sacrificio_eucaristico: { to: "/missa#liturgia-eucaristica" },
  sagrada_comunhao: { to: "/missa#comunhao" },
  santissimo_sacramento: { to: "/missa#liturgia-eucaristica" },
  segunda_leitura: { to: "/missa#liturgia-da-palavra" },
  turibulo: { to: "/artigos-religiosos" },
  uncao_enfermos: { to: "/sacramentos" },
  velas: { to: "/artigos-religiosos" },
  visitas_enfermos: { to: "/sacramentos" },
  calendario_liturgico_maiusculo: { to: "/ano-liturgico" },
  calendario_liturgico_contexto: { to: "/ano-liturgico" },
  sabado: { to: "/ano-liturgico" },
  ministros: { to: "/ritos" },
  sacerdote: { to: "/ritos" },
  diacono: { to: "/ritos" },
  presbiterio: { to: "/ritos" },
  incenso: { to: "/ritos" },
  cruz_processional: { to: "/ritos" },
  velas_processionais: { to: "/ritos" },
  ano_liturgico: { to: "/ano-liturgico" },
  ano_liturgico_verde: { to: "/ano-liturgico" },
  ano_liturgico_rosa: { to: "/ano-liturgico" },
  altar: { to: "/missa" },
  velas_liturgicas: { to: "/ritos" },
  missal: { to: "/ritos" },
  missal_romano: { to: "/ritos" },
  confesso_deus: { to: "/oracoes" },
  sacramento_reconciliacao: { to: "/sacramentos" },
  kyrie_eleison: { to: "/oracoes" },
  gloria: { to: "/oracoes" },
  aleluia: { to: "/oracoes" },
  advento: { to: "/ano-liturgico#advento" },
  gaudete: { to: "/ano-liturgico#gaudete" },
  quaresma: { to: "/ano-liturgico#quaresma" },
  laetare: { to: "/ano-liturgico#laetare" },
  pascoa: { to: "/ano-liturgico#triduo-pascal" },
  natal: { to: "/ano-liturgico#tempo-natal" },
  tempo_comum: { to: "/ano-liturgico#tempo-comum-primeira-parte" },
  pentecostes: { to: "/ano-liturgico#pentecostes" },
  domingo_ramos: { to: "/ano-liturgico#semana-santa" },
  sexta_feira_santa: { to: "/ano-liturgico#triduo-pascal" },
  // Mantém compatibilidade com a grafia já usada nos textos traduzidos.
  sexta_Feira_santa: { to: "/ano-liturgico#triduo-pascal" },
  finados: { to: "/ano-liturgico#finados" },
  solenidades: { to: "/ano-liturgico#datas-principais" },
  grandes_solenidades: { to: "/ano-liturgico#datas-principais" },
  festas: { to: "/ano-liturgico#datas-principais" },
  calendario_liturgico: { to: "/ano-liturgico" },
  tempo_pascal: { to: "/ano-liturgico#tempo-pascal" },
  lecionario_romano: { to: "/ritos" },
  vestes_liturgicas: { to: "/ritos" },
  exequias: { to: "/ritos" },
  rito_romano: { to: "/ritos" },
  missal_sao_paulo_vi: { to: "/ritos" },
  novus_ordo: { to: "/ritos" },
  sacramentos: { to: "/sacramentos" },
  batismo: { to: "/sacramentos" },
  batismos: { to: "/sacramentos" },
  pia_batismal: { to: "/sacramentos" },
  verde: { to: "/missa#verde" },
  roxo: { to: "/missa#roxo" },
  rosa: { to: "/missa#rosa" },
  branco: { to: "/missa#branco" },
  branca: { to: "/missa#branco" },
  vermelha: { to: "/missa#vermelho" },
  vermelho: {
    to: "/missa#vermelho",
    translationKey: "palavras_chave.vermelho_maiusculo",
  },
  cirio_pascal: { to: "/artigos-religiosos" },
  presepio: { to: "/artigos-religiosos" },
  corpus_christi: { to: "/missa#liturgia-eucaristica" },
  sagrado_coracao: { to: "/oracoes" },
  vinde_espirito_santo: { to: "/oracoes" },
  santo: { to: "/oracoes#santo" },
  epiclese: { to: "/ritos" },
  sineta_liturgica: { to: "/artigos-religiosos" },
  sacramento_ordem: { to: "/sacramentos" },
  in_persona_christi: { to: "/ritos" },
  pai_nosso: { to: "/oracoes" },
  cordeiro_deus: { to: "/oracoes" },
  eucaristia: { to: "/sacramentos" },
  oracao: { to: "/oracoes" },
  oracao_eucaristica: { to: "/missa#liturgia-eucaristica" },
  vigilia_pascal: { to: "/ano-liturgico#triduo-pascal" },
  medalha_sao_bento: { to: "/artigos-religiosos#artigos-devocionais" },
};

// Os santos com data própria permanecem separados para facilitar o calendário.
const saintLinks: Record<string, KeywordLink> = {
  sao_domingos: { to: "/santos" },
  sao_pio: { to: "/santos" },
  agostinho: { to: "/santo-do-dia?data=2026-08-28" },
  santa_maria_madalena: { to: "/santo-do-dia?data=2026-07-22" },
  santa_missa: { to: "/missa" },
  santo_agostinho: { to: "/santo-do-dia?data=2026-08-28" },
  santo_ambrosio: { to: "/santo-do-dia?data=2026-12-07" },
  santo_terco: { to: "/artigos-religiosos", translationKey: "palavras_chave.terco" },
  sao_bento: { to: "/santo-do-dia?data=2026-07-11" },
  sao_tomas_aquino: { to: "/escolastica" },
  sao_mateus: { to: "/santos" },
  sao_marcos: { to: "/santos" },
  sao_lucas: { to: "/santos" },
  sao_joao: { to: "/santos" },
  sao_joao_paulo_ii: { to: "/santo-do-dia?data=2026-10-22" },
  santa_faustina: { to: "/santo-do-dia?data=2026-10-05" },
  sao_joao_batista: { to: "/santo-do-dia?data=2026-06-24" },
  sao_pedro_sao_paulo: { to: "/santo-do-dia?data=2026-06-29" },
  assuncao_virgem_maria: { to: "/santo-do-dia?data=2026-08-15" },
  exaltacao_santa_cruz: { to: "/santo-do-dia?data=2026-09-14" },
  todos_os_santos: { to: "/santo-do-dia?data=2026-11-01" },
  santos: { to: "/santos" },
  santo_estevao: { to: "/santos" },
  santos_inocentes: { to: "/santos" },
  martires: { to: "/santos" },
  martirio: { to: "/santos" },
  santa_maria: { to: "/dogmas-marianos" },
  nossa_senhora_aparecida: { to: "/santos" },
  maria: { to: "/santos" },
  sao_miguel_arcanjo: { to: "/santos" },
  santo_inacio: { to: "/santo-do-dia?data=2026-07-31", translationKey: "palavras_chave.santo_inacio_loyola" },
  santo_afonso: { to: "/santo-do-dia?data=2026-08-01", translationKey: "palavras_chave.santo_afonso_ligorio", class: "font-bold" },
  sao_rabano: { to: "/santo-do-dia?data=2026-02-04", translationKey: "palavras_chave.sao_rabano_mauro" },
  nossa_senhora: { to: "/dogmas-marianos" },
  aparicao_fatima: { to: "/santo-do-dia?data=2026-05-13" },
  papa_leao_xiii: { to: "/papado" },
  sao_miguel: { to: "/santo-do-dia?data=2026-09-29" },
  sao_policarpo: { to: "/santo-do-dia?data=2026-02-23" },
};

// Referências oficiais abrem fora do site e sempre em uma nova aba.
const externalReferences: Record<string, KeywordLink> = {
  cic2157: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p3s2cap1_2083-2195_po.html#2157",
    external: true,
    text: "CIC 2157",
  },
  cic336: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p1s2c1_198-421_po.html#336",
    external: true,
    text: "CIC 336",
  },
  cic188_194: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p1s2_185-197_po.html#188",
    text: "CIC 188, 194",
    external: true,
  },
  cic1254: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p2s2cap1_1210-1284_po.html#1254",
    external: true,
    text: "CIC 1254",
  },
  catecismo2180_2181: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p3s2cap1_2083-2195_po.html#2180",
    external: true,
  },
  catecismo1667: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p2s2cap4_1667-1690_po.html#2111",
    external: true,
  },
  catecismo2111: {
    to: "https://www.vatican.va/archive/cathechism_po/index_new/p3s2cap1_2083-2195_po.html#2111",
    external: true,
  },
};

// Este é o catálogo consumido pelo RichText. As divisões acima servem apenas
// para manter o arquivo legível conforme novas páginas e palavras forem criadas.
export const keywordLinks: Record<string, KeywordLink> = {
  ...doctrineLinks,
  ...liturgyLinks,
  ...saintLinks,
  ...externalReferences,
};
